### ISSUE TITLE
Not working properly with filtered list

### ISSUE THREAD

**Issue by p32929** [ValentinH/react-easy-sort#30]
Hello, first of all, thanks for making/maintaining this amazing library.

**Describe the bug**
Showing weird behavior if a filtered list is used to rerrange

**To Reproduce**
1. Go to https://codesandbox.io/s/misty-tree-0ispk4
2. Try to rearrange A with C
3. You will see, A becomes B
4. Try to rearrange G with I
5. You will see, it doesn't work

Here's a gif with a demo of the issue explained above:
![res](https://user-images.githubusercontent.com/6418354/183491950-d5b680aa-5ca6-430d-b229-f95d3abd27a6.gif)

**Expected behavior**
The rearranged list should work properly/correctly

**Comment by ValentinH** [comment]
Thanks for the kind words!

The issue in your example comes from the fact that the `onSortEnd` callback gives you the indexes of the items that changed in the "filtered" list (the one that is passed to the `SortableList` but you apply the change using these indexes on the original non-filtered array.

I see 2 possible solutions:
- storing the filtered list in the state (easier)
- converting the indexes from the filtered list to the unfiltered list before switching the items

**Comment by ValentinH** [comment]
When switching G and I, you can see that E becomes D. This is because G and I are indexes 3 and 4 in the filtered array: when inverting these indexes in the original array, you actually switch D and E. That's why you see D becoming E. 🙂

**Comment by p32929** [comment]
Awesome. Thanks a lot for the explanation.
Have a wonderful day...
