### ISSUE TITLE
`allowDrag` prop not working on mobile devices

### ISSUE THREAD

**Issue by devon66h** [ValentinH/react-easy-sort#31]
**Describe the bug**
Setting the prop `allowDrag={false}` works on desktop, but not on mobile devices. 

This bug has been observed across both iOS and Android, and across Chrome, Safari & Firefox.

**To Reproduce**

1. Set `allowDrag={false}`
2. Open hosted app on a mobile device
3. Test to see if you're able to drag items

**Expected behavior**
Expect dragging to be disabled on mobile devices

**Comment by ValentinH** [comment]
Hi, good catch!

Indeed, as touch events are attached in a different manner that the desktop ones, the `allowDrag` logic was not probably added for touch devices 🙈 

The fix should be fairly easy: this whole block inside the `useDrag()` hook should be ignored if `allowDrag` is false
https://github.com/ValentinH/react-easy-sort/blob/main/src/hooks.ts#L211-L223

Would you like to submit a PR for this?

**Comment by devon66h** [comment]
> Hi, good catch!
> 
> Indeed, as touch events are attached in a different manner that the desktop ones, the `allowDrag` logic was not probably added for touch devices 🙈
> 
> The fix should be fairly easy: this whole block inside the `useDrag()` hook should be ignored if `allowDrag` is false https://github.com/ValentinH/react-easy-sort/blob/main/src/hooks.ts#L211-L223
> 
> Would you like to submit a PR for this?

Hey thanks for responding so quickly!

When I clone and try to push my branch changes to this repo it says I don't have permission? I may be doing something wrong

**Comment by devon66h** [comment]
> Hi, good catch!
> 
> Indeed, as touch events are attached in a different manner that the desktop ones, the `allowDrag` logic was not probably added for touch devices 🙈
> 
> The fix should be fairly easy: this whole block inside the `useDrag()` hook should be ignored if `allowDrag` is false https://github.com/ValentinH/react-easy-sort/blob/main/src/hooks.ts#L211-L223
> 
> Would you like to submit a PR for this?

@ValentinH Here ya go 😄 
https://github.com/ValentinH/react-easy-sort/pull/32
