### ISSUE TITLE
Node.js v16 support

### ISSUE THREAD

**Issue by elukoyanov** [ValentinH/react-easy-sort#38]
**Describe the bug**
Node.js 16 is not supported anymore by package.json engine restricrion.

**Expected behavior**
Node.js v16 package installation works.

**Is your feature request related to a problem? Please describe.**
Project is worked on Node v16 and hasn't changed breakingly.

**Describe the solution you'd like**
Change engine to `">=16"` or "^16 || >=18"

**Describe alternatives you've considered**
none

**Additional context**
Package works in v16, but you restricted to install in it

**Comment by ValentinH** [comment]
Sorry for the delay, this is fixed in https://github.com/ValentinH/react-easy-sort/releases/tag/v1.5.3
