### ISSUE TITLE
Get to control the transition duration or snap on origin control function ?

### ISSUE THREAD

**Issue by fzsf163** [ValentinH/react-easy-sort#42]
# Is there a way to control the transition duration or control behaviour after drop ?

If I apply transition from outside , entire lay out gets destroyed.

Can we please get an option to control transition duration or  snap on origin function. Where we can decide how it will be act after drag completion. Like bounce effect or slower snap to drop zone.

**Comment by ValentinH** [comment]
This would require quite a lot of changes to the implementation.
Indeed, during the drag, we don't move the actual item but a copy of it.
When the gesture starts, we clone the item and hide the item. Then, we translate the clone during the gesture. Finally, on drop, we delete the clone and show back the item.

Adding a transition on drop would require 2 things:
- delaying the deletion of the clone
- adding an animation toward the new position

**Comment by fzsf163** [comment]
Please if possible , implement it. This is one of the best and easiest libs to use for drag and drop.

**Comment by fzsf163** [comment]
Okk okk good enough. Thank you so much for making this lib.
